# Generated by Django 3.2.8 on 2021-11-30 14:34

import activities.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('action_to_be_performed', models.CharField(max_length=255)),
                ('icon', models.ImageField(help_text='Choose an icon to represent the activity', upload_to=activities.models.activity_directory_path)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='activities.activity')),
                ('animals', models.ManyToManyField(related_name='events', to='animals.Animal')),
            ],
            options={
                'ordering': ['-datetime'],
                'permissions': (('search', 'Can do research in events'),),
            },
        ),
    ]
