"""
Django settings for Balto project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import netifaces

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sdv=@5@l(ml+&odwd@@4o^a&o5vhv3u8pac5xg@s=zmn-fs^d$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ----------- if you don't want to see the site on other devices inside your LAN remove this block of code -----------
allowed = ''
for i in netifaces.interfaces():
    if i != 'lo':
        try:
            ip = str(netifaces.ifaddresses(i)[netifaces.AF_INET][0]['addr'])
            if str(ip).startswith('192.168.'):
                allowed = ip
        except KeyError:
            pass
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', allowed if DEBUG else '']  # run on terminal: python manage.py runserver 0.0.0.0:8000
# ----------- delete to here and set: ALLOWED_HOSTS = []  -----------

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # My apps
    'users.apps.UsersConfig',
    'animals.apps.AnimalsConfig',
    'activities.apps.ActivitiesConfig',
    'notifications.apps.NotificationsConfig',
    'facility.apps.FacilityConfig',
    # Other apps
    'crispy_forms',
    'sslserver',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Configurations.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.my_notifications'
            ],
        },
    },
]

WSGI_APPLICATION = 'Configurations.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Rome'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy form
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Images upload
MEDIA_ROOT = BASE_DIR / 'static' / 'images' / 'apps'

# Login and Users
AUTH_USER_MODEL = 'users.User'

LOGIN_URL = 'users:user-login'

LOGIN_REDIRECT_URL = 'homepage'

# Prohibited permissions for users managed by the 'users' app
prohibited_permissions = [
    # -- logentry --
    'add_logentry',
    'change_logentry',
    'delete_logentry',
    'view_logentry',
    # -- permission --
    'add_permission',
    'change_permission',
    'delete_permission',
    # 'view_permission',
    # -- contenttype --
    'add_contenttype',
    'change_contenttype',
    'delete_contenttype',
    'view_contenttype',
    # -- session --
    'add_session',
    'change_session',
    'delete_session',
    'view_session',
]
