# Generated by Django 3.2.8 on 2021-11-30 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
            ],
            options={
                'permissions': (('view_my_notifications', 'Can view his own notifications'), ('change_my_notifications', 'Can change his own notifications'), ('delete_my_notifications', 'Can delete his own notifications')),
            },
        ),
        migrations.CreateModel(
            name='RecipientsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
